#! /bin/sh

sxhkd &

bspc config border_width         4
bspc config window_gap          10

bspc config focused_border_color "#00FF00"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config top_padding 15

bspc monitor -d I II III IV V VI

#bspc wm -d
bspc rule --add URxvt:scratchpad sticky=on state=floating
bspc rule --add Thunar:thunar state=floating
bspc rule --add Spotify:spotify state=floating
bspc rule --add Cinelerra:cinelerra state=floating
bspc rule --add xzoom state=floating

xsetroot -cursor_name left_ptr
#panel &
$HOME/.config/bspwm/launchPolybar.sh &
