#!/bin/bash

projectPath=$1

if [ ! -d "${projectPath}" ]; then
    echo 'Need a valid Project path'
    exit 1
fi

plotsPath="${projectPath}/Plots"
if [ -d "${plotsPath}" ]; then
    echo 'Plots directory already exists'
    exit 1
fi
graphsPath="${plotsPath}/Graphs"
csvPath="${plotsPath}/Data"

mkdir "${plotsPath}"
mkdir "${graphsPath}"
mkdir "${csvPath}"

for A in "${projectPath}"/A*; do
    cp "${A}"/radiusplot_*pdf "${graphsPath}"
    cp "${A}"/radius_*dat "${csvPath}"
done
