#!/usr/bin/python3

import sys

if len(sys.argv) == 2:
    print(f"{sys.argv[1]} = \n\t{eval(sys.argv[1]):,}")
else:
    import gi
    gi.require_version('Notify', '0.7')
    from gi.repository import Notify
    Result = Notify.Notification.new(f"Python {sys.version.split(' ')[0]} Calculator",
            f"{sys.argv[1]} = \n{eval(sys.argv[1]):,}", "dialog-information")
    Result.show()
