#!/bin/bash

controlConfig=$1
temperature=$2
Avalue=$3

counter=1
newName="temp${counter}"
while [ -d "${newName}" ]; do
    let counter++
    newName="temp${counter}"
done
mkdir "${newName}"
cd "${newName}"

echo "Creating Input files for Temperature: ${temperature} and A: ${Avalue}..."
createInput "${controlConfig}" "${temperature}" "${Avalue}"

rm polymer.dat coords.dat

dpd

sleep 1
Traject 1
radius.exe 1
echo 'Final Radius of Gyration: ' $(tail -n1 radius_polymer | awk '{print $4}')
